### ISSUE TITLE
Answer on "Fuente del turia"

### ISSUE THREAD

**Issue by Simbalg** [mamiavi/igsmApp#36]
Audio says "Tribunal de les aigües" does reunite every Saturday, but the options only show thursday, sunday and wednesday
![imagen](https://github.com/mamiavi/igsmApp/assets/137925983/279d9aac-9450-486d-a2f0-197a128d9f41)

**Comment by Simbalg** [comment]
I fact checked on google, it's actually on Thursdays!

**Comment by mamiavi** [comment]
Solved in PR #40
