### ISSUE TITLE
Wrong question and wrong answers in "Plaza Redonda"

### ISSUE THREAD

**Issue by Simbalg** [mamiavi/igsmApp#38]
The audio says "Plaza redonda" has an entrance for every cardinal point, which sets the answer for the question of the POI. But that is wrong, as in the image we can see it has two on the north and and one on west and east.
![imagen](https://github.com/mamiavi/igsmApp/assets/137925983/ef511564-3fcf-4ad4-8d38-d64765ede808)

**Comment by mamiavi** [comment]
Solved in #41
